name: CI
on: push

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.repository == 'depot/amis'
    steps:
      - uses: actions/checkout@v3
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ubuntu-20.04.pkr.hcl
          working_directory: github-actions

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::375021575472:role/github-actions-builder-images

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var 'ami-name=depot-github-actions-ubuntu-20.04-snapshot'"
          target: ubuntu-20.04.pkr.hcl
          working_directory: github-actions
        env:
          PACKER_LOG: 1
